### ISSUE TITLE
Q: Why keeps value constant？

### ISSUE THREAD

**Issue by nnuzi** [sindresorhus/temp-dir#2]
Due to  
https://github.com/sindresorhus/temp-dir/blob/4337f7757f4aac3c9531f9e712e603caf63adf1b/index.js#L7-L11 
`fs.realpathSync(os.tmpdir())` are invoked only when the property is defined.

This cause I can not use lazy evaluation to ensure a varied-result for each time I use.

Why do you do it this way(for some reason) or whether needs export new fn ` API = () => fs.realpathSync(os.tmpdir()) `?

**Comment by nnuzi** [comment]
Emmm ...  I found `os.tmpdir()` return the same string, that because operating system's only assign one default directory for temporary files?

**Comment by kevva** [comment]
This module is not meant to be used to get a random temporary path. Use https://github.com/sindresorhus/tempy for that. This module only returns the temporary directory for your OS.

> Emmm ... I found os.tmpdir() return the same string, that because operating system's only assign one default directory for temporary files?

From the readme:

> The os.tmpdir() built-in doesn't return the real path. That can cause problems when the returned path is a symlink, which is the case on macOS. Use this module to get the resolved path.
