### ISSUE TITLE
realpathSync to realpathSync.native

### ISSUE THREAD

**Issue by privatenumber** [sindresorhus/temp-dir#5]
In Windows, doing `fs.realpathSync(os.tmpdir())` doesn't resolve the symlink. You must do `fs.realpathSync.native(os.tmpdir())`.

However, I'm not sure if it is always safe to use: https://github.com/nodejs/node/issues/39721

**Comment by sindresorhus** [comment]
> In Windows, doing fs.realpathSync(os.tmpdir()) doesn't resolve the symlink.

Sounds like this should be fixed in Node.js instead.

**Comment by privatenumber** [comment]
As I understand it, `fs.realpathSync.native` is the fix to `fs.realpathSync`. 

The promise version [`fsPromises.realpath(path[, options])`](https://nodejs.org/api/fs.html#fspromisesrealpathpath-options) behaves like `fs.realpathSync.native`, and there is no promise version of `fs.realpathSync`.

**Comment by privatenumber** [comment]
Thanks @Richienb 

I recommend testing in Windows too moving forward as this issue was surfaced as a result of Window's specific behavior.
